<a href="https://colab.research.google.com/github/sharaaz-ux/AI-Powered-Workforce-Analytics-Talent-Intelligence-Dashboard/blob/main/Week1/SQL_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here is the SQL task

In [1]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("company.db")
cursor = conn.cursor()
cursor.execute("DROP TABLE IF EXISTS Employees")
cursor.execute("""
CREATE TABLE Employees (
    EmpID INTEGER PRIMARY KEY,
    Name TEXT,
    Department TEXT,
    Salary INTEGER,
    Experience INTEGER
)
""")
employees = [
    (1, "Rahul", "IT", 60000, 2),
    (2, "Aisha", "HR", 45000, 3),
    (3, "Kiran", "IT", 70000, 5),
    (4, "Priya", "Finance", 80000, 6),
    (5, "John", "Marketing", 50000, 2),
    (6, "Sara", "HR", 55000, 4),
    (7, "Rohan", "IT", 90000, 8),
    (8, "Meera", "Finance", 65000, 3)
]

cursor.executemany("INSERT INTO Employees VALUES (?, ?, ?, ?, ?)", employees)
conn.commit()

print("\n--- All Employees Data ---")
display(pd.read_sql("SELECT * FROM Employees", conn))

print("\n--- Employees with Salary > 60000 ---")
display(pd.read_sql("""
SELECT Name, Salary
FROM Employees
WHERE Salary > 60000
""", conn))

print("\n--- Average Salary by Department ---")
display(pd.read_sql("""
SELECT Department,
AVG(Salary) AS Average_Salary
FROM Employees
GROUP BY Department
""", conn))

print("\n--- Employees with Experience > 3 years ---")
display(pd.read_sql("""
SELECT *
FROM Employees
WHERE Experience > 3
""", conn))

print("\n--- Employee with the Highest Salary ---")
display(pd.read_sql("""
SELECT *
FROM Employees
ORDER BY Salary DESC
LIMIT 1
""", conn))

cursor.execute("""
DELETE FROM Employees
WHERE EmpID = 5
""")

conn.commit()

conn.close()

--- All Employees Data ---

   EmpID   Name Department  Salary  Experience
0      1  Rahul         IT   60000           2
1      2  Aisha         HR   45000           3
2      3  Kiran         IT   70000           5
3      4  Priya    Finance   80000           6
4      5   John  Marketing   50000           2
5      6   Sara         HR   55000           4
6      7  Rohan         IT   90000           8
7      8  Meera    Finance   65000           3

--- Employees with Salary > 60000 ---

    Name  Salary
0  Kiran   70000
1  Priya   80000
2  Rohan   90000
3  Meera   65000

--- Average Salary by Department ---

  Department  Average_Salary
0    Finance    72500.000000
1         HR    50000.000000
2         IT    73333.333333
3  Marketing    50000.000000

--- Employees with Experience > 3 years ---

   EmpID   Name Department  Salary  Experience
0      3  Kiran         IT   70000           5
1      4  Priya    Finance   80000           6
2      6   Sara         HR   55000           4
3      7  Rohan         IT   90000           8

--- Employee with the Highest Salary ---

   EmpID   Name Department  Salary  Experience
0      7  Rohan         IT   90000           8